text_keywords:
  - "documento"
  - "identificacion"
  - "identificación"
  - "no_id"
  - "codigo"
  - "código"
  - "cod"
  - "cód"
  - "Código de habilitación"
  - "dane"
  - "ciudad"
  - "nombre"
  - "número de autorización"
  - "año"
  - "mes"
  - "anio"
  - "aut"
  - "cum"
  - "num_afiliado"
  - "id"

float_keywords:
  - "costo"
  - "total"
  - "valor"
  - "vr"
  - "tope"

date_formats:
  - "%Y-%m-%d"
  - "%d/%m/%Y"
  - "%d-%m-%Y"
  - "%Y/%m/%d"

boolean_true_values:
  - "true"
  - "yes"
  - "verdadero"
  - "si"
  - "sí"

boolean_false_values:
  - "false"
  - "no"
  - "falso"